### ISSUE TITLE
ItemDefinitionIndex

### ISSUE THREAD

**Issue by NullFlex** [Vitalflea/Castle#1]
Getting some errors in ItemDefinitionIndex.
Error spot:

`enum ItemDefinitionIndex GetItemIndex(const std::string);`

Error code:

`Error    C3431    'ItemDefinitionIndex': a scoped enumeration cannot be redeclared as an unscoped enumeration`

**Comment by atiwiex** [comment]
Its a ghetto fix but remove enum infront of ItemDefinitionIndex

**Comment by NullFlex** [comment]
@atiwiex worked, but now I crash when joining a game.
