### ISSUE TITLE
Crash when joining a game.

### ISSUE THREAD

**Issue by NullFlex** [Vitalflea/Castle#2]
Fixed the enum stuff, but now I crash when joining a game. Any help? @atiwiex @vitalflea

**Comment by plasmafart** [comment]
Not getting any crashes my self, mind telling me what settings you use

**Comment by atiwiex** [comment]
I'm not getting any either. Can you give me your config for the cheat

**Comment by mew351** [comment]
Did you guys update offsets?
Mine crashes aswell @NullFlex @plasmafart @atiwiex

**Comment by atiwiex** [comment]
@mew351 nope

**Comment by mew351** [comment]
@atiwiex and you can load into a map just fine?

**Comment by atiwiex** [comment]
@mew351 yep

**Comment by mew351** [comment]
Mind uploading yours to github @atiwiex or sending me it on Discord?
Add my Discord - God#0001

**Comment by atiwiex** [comment]
I'll upload to GitHub and then send the link over discord

**Comment by mew351** [comment]
Okay! Thanks so much!
What's your Discord ID?

**Comment by atiwiex** [comment]
Added - William#0660

**Comment by mew351** [comment]
@plasmafart mind adding my Discord?

**Comment by plasmafart** [comment]
All I did was fix the enum errors and compile, not getting any crash even after the update.

**Comment by NullFlex** [comment]
@mew351 @plasmafart seems to be a problem in renderview. Github has been updated, going to test when i get home.

**Comment by NullFlex** [comment]
@Vitalflea pull my request. I removed all the fixed / untrusted bs

**Comment by mew351** [comment]
That was the problem @NullFlex I got it working last night haha

What were the untrusted bs?

**Comment by NullFlex** [comment]
@mew351 teleport, angel
@Vitalflea the renderview thing did work, but the visuals dont work.
