### ISSUE TITLE
Not an Issue ;)

### ISSUE THREAD

**Issue by ShiningMatter** [Vitalflea/Castle#6]
As you might know, I've seen the "p2c providers selling this cheat" header, and I wanted to declare that I'm not really doing anything unmoral, like scamming or anything. What I'm doing is modifying the source code, making it UD, add/remove some stuff, then compile it. I also use more methods to further improve the cheat even more UD. I'm just selling this for 1$, and that's because I'm helping the people who are afraid of breaking the code, or do not want to go through the trouble of installing Visual Studio. Or those who don't know how to hook up the ImGUI folder, or the SDK. So, Vitaldlea, thank you for reading this, and if you ever want me to not use your source, I wouldn't mind stopping, like I'm not even making hardly any profit of this. I just want to help people :)

**Comment by Vitalflea** [comment]
https://imgur.com/a/Xursb
